Super gross hack to make configure match

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -391,7 +391,7 @@ DSOSUF=".so"
 LDFLAGS_SHARED="-shared"
 modules="no"
 prefix="/usr/local"
-mandir="\${prefix}/share/man"
+mandir="\${prefix}/man"
 datadir="\${prefix}/share"
 firmwarepath="\${prefix}/share/qemu-firmware"
 qemu_docdir="\${prefix}/share/doc/qemu"
@@ -466,8 +466,12 @@ vte=""
 virglrenderer=""
 tpm="yes"
 libssh2=""
+vhdx=""
+quorum="no"
+pcap="no"
+pcap_create="no"
+bpf="no"
 live_block_migration="yes"
-numa=""
 tcmalloc="no"
 jemalloc="no"
 replication="yes"
@@ -1086,6 +1090,10 @@ for opt do
   --disable-vnc-png) vnc_png="no"
   ;;
   --enable-vnc-png) vnc_png="yes"
+  ;;
+  --enable-pcap) pcap="yes"
+  ;;
+  --disable-pcap) pcap="no"
   ;;
   --disable-slirp) slirp="no"
   ;;
@@ -3077,6 +3085,50 @@ EOF
   fi
 fi
 
+##########################################
+# pcap probe
+
+if test "$pcap" = "yes" -a "$pcap" != "no"; then
+  cat > $TMPC << EOF
+#include <pcap.h>
+int main(void) { return (pcap_lib_version() == (char *)0 ? 1 : 0); }
+EOF
+  if test "$mingw32" = "no" ; then
+    libpcap=-lpcap
+  else
+    libpcap=-lwpcap
+  fi
+  if compile_prog "" "$libpcap" ; then
+    :
+  else
+    echo
+    echo "Error: Could not find pcap"
+    echo "Make sure to have the pcap libs and headers installed."
+    echo
+    exit 1
+  fi
+  cat > $TMPC << EOF
+#include <pcap.h>
+int main(void)
+{
+  char errbuf[PCAP_ERRBUF_SIZE];
+  return (pcap_create("foo", errbuf) == (pcap_t *)0 ? 1 : 0);
+}
+EOF
+  if compile_prog "" "$libpcap" ; then
+    pcap_create="yes"
+  fi
+  cat > $TMPC << EOF
+#define PCAP_DONT_INCLUDE_PCAP_BPF_H
+#include <pcap.h>
+#include <net/bpf.h>
+int main(void) { return (BPF_MAJOR_VERSION); }
+EOF
+  if compile_prog ; then
+    bpf="yes"
+  fi
+  libs_softmmu="$libpcap $libs_softmmu"
+fi # test "$pcap"
 
 ##########################################
 # VNC SASL detection
@@ -4434,15 +4486,18 @@ if compile_prog "" "" ; then
 fi
 
 # Check if tools are available to build documentation.
+#if test "$docs" != "no" ; then
+#  if has makeinfo && has pod2man; then
+#    docs=yes
+#  else
+#    if test "$docs" = "yes" ; then
+#      feature_not_found "docs" "Install texinfo and Perl/perl-podlators"
+#    fi
+#    docs=no
+#  fi
+#fi
 if test "$docs" != "no" ; then
-  if has makeinfo && has pod2man; then
-    docs=yes
-  else
-    if test "$docs" = "yes" ; then
-      feature_not_found "docs" "Install texinfo and Perl/perl-podlators"
-    fi
-    docs=no
-  fi
+  docs=yes
 fi
 
 # Search for bswap_32 function
@@ -4567,6 +4622,17 @@ fi
 
 # check for libusb
 if test "$libusb" != "no" ; then
+    cat > $TMPC << EOF
+#include <libusb.h>
+
+int main(void) { return libusb_get_port_path(NULL, NULL, NULL, 0); }
+EOF
+    if compile_prog "-Werror" "-lusb -pthread" ; then
+        libusb="yes"
+        libusb_cflags=""
+        libusb_libs=-lusb
+        libs_softmmu="$libs_softmmu $libusb_libs"
+    else
     if $pkg_config --atleast-version=1.0.13 libusb-1.0; then
         libusb="yes"
         libusb_cflags=$($pkg_config --cflags libusb-1.0)
@@ -4576,6 +4642,7 @@ if test "$libusb" != "no" ; then
             feature_not_found "libusb" "Install libusb devel >= 1.0.13"
         fi
         libusb="no"
+    fi
     fi
 fi
 
@@ -5930,6 +5997,7 @@ echo "Audio drivers     $audio_drv_list"
 echo "Block whitelist (rw) $block_drv_rw_whitelist"
 echo "Block whitelist (ro) $block_drv_ro_whitelist"
 echo "VirtFS support    $virtfs"
+echo "pcap support      $pcap"
 echo "Multipath support $mpath"
 echo "VNC support       $vnc"
 if test "$vnc" = "yes" ; then
@@ -6158,6 +6226,15 @@ if test "$static" = "yes" ; then
 fi
 if test "$profiler" = "yes" ; then
   echo "CONFIG_PROFILER=y" >> $config_host_mak
+fi
+if test "$pcap" = "yes" ; then
+  echo "CONFIG_PCAP=y" >> $config_host_mak
+  if test "$pcap_create" = "yes" ; then
+    echo "CONFIG_PCAP_CREATE=y" >> $config_host_mak
+  fi
+  if test "$bpf" = "yes" ; then
+    echo "CONFIG_BPF=y" >> $config_host_mak
+  fi
 fi
 if test "$slirp" = "yes" ; then
   echo "CONFIG_SLIRP=y" >> $config_host_mak
