bsd-user-smoke: Import sources and build them
make check now will run the binaries we generated from the sources. This
could be a submodule, but that would be way more effort than my keeping
this in sync with whatever changes I might make to my hello repo (since
I plan no changes and these sources have been reviewed by domain experts
there). Also, these will eventually go away when I've upstreamed enough
to move to the tcg tests (they are a good start at the moment, but a
little tricky to use, while these are easy since they are self
contained). All these hello-world programs are statically linked
binaries that are less than a page...

Signed-off-by: Warner Losh <imp@bsdimp.com>

diff --git a/tests/bsd-user-smoke/runit b/tests/bsd-user-smoke/runit
--- a/tests/bsd-user-smoke/runit
+++ b/tests/bsd-user-smoke/runit
@@ -1,13 +1,13 @@
 #!/bin/sh
 
-src=$1
-build=$2
+build=$1
+testing=$2
 
 doit() {
 	local a=$1 q=$2
 
 	echo Hello World > foo1
-	$build/qemu-$q $src/h.$a > foo2 || die "cmd failed: $build/qemu-$q $src/h.$a"
+	$build/qemu-$q $testing/h.$a > foo2 || die "cmd failed: $build/qemu-$q $testing/h.$a"
 	cmp foo1 foo2 || die "Hello World expected"
 	rm foo1 foo2
 }
